### ISSUE TITLE
EPIC: Students can apply to use the Gauchoride service, and admins can manage applications : #1 Create database record and fixtures

### ISSUE THREAD

**Issue by Daoyijiucsb** [ucsb-cs156-w24/proj-gauchoride-w24-7pm-1#17]
# First issue:  Create database record and fixtures

- [ ] There is an `@Entity` called `RiderApplication` with fields: `Long id`, `String status`, `Long userId`, `String perm_number`, `Date created_date`, `Date updated_date`, `Date cancelled_date`, `String description` , `String notes`
- [ ] There is a `@Repository` called `RiderApplicationRepository` 
- [ ] There is a fixtures files `riderApplicationFixtures.js`
